kind: Service
apiVersion: v1
metadata:
  name: currencyexchange
  labels:
    app: currencyexchange
spec:
  ports:
    - name: 9201-tcp
      protocol: TCP
      port: 9201
      targetPort: 9201
  selector:
    app: currencyexchange
    deploymentconfig: currencyexchange