kind: Service
apiVersion: v1
metadata:
  name: ui
  labels:
    app: ui
spec:
  ports:
    - name: 9000-tcp
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: ui
    deploymentconfig: ui